version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    networks:
      - springmysql-net
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: stationSki

  app:
    depends_on:
      - mysqldb
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    networks:
      - springmysql-net
    env_file:
      - .env
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stationSki?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

networks:
  springmysql-net:

volumes:
  db:
